### PR TITLE
WIP: docker-compose-no-mesos.yml to cross-check e2e tests without Mesos

### PR DESCRIPTION
**Pull request by sttts**
Implementing mesosphere/kubernetes-mesos#383.

### CODE REVIEW

**Comment by sttts** [comment]
quick'n'dirty

**Comment by karlkfi** [comment]
Gonna want this under cluster/docker so it can be launched with KUBERNETES_PROVIDER=docker

**Comment by sttts** [comment]
Sure. This was just a quick hack. 

Might be worth it to refactor that both directories share the same code.

**Comment by jdef** [comment]
is this still useful?

**Comment by karlkfi** [comment]
See https://github.com/mesosphere/kubernetes-mesos/issues/383#issuecomment-130103985 for reasoning.

**Pull request closed without merging**
