### PR TITLE
Getting started guide

### PR DESCRIPTION
**Pull request by jdef**
- updated for v0.4 release of k8sm
- added link to mesos.md in README.md

### CODE REVIEW

**Comment by jdef** [comment]
https://github.com/mesosphere/kubernetes-mesos/issues/122

**Comment by jdef** [comment]
https://github.com/mesosphere/kubernetes-mesos/issues/154

**Comment by jdef** [comment]
xref https://github.com/mesosphere/website/pull/539

**Comment by jdef** [comment]
**UPDATE** this work is complete.

It probably also makes sense to update:
- https://github.com/mesosphere/kubernetes/blob/master/docs/getting-started-guides/README.md

Something like:
- infra: Mesos/GCE
- config: (blank)
- os: (blank)
- networking: (blank)
- support: Community

cc @ConnorDoyle

**Comment by jdef** [comment]
ready for review PTAL

**Comment by ConnorDoyle** [comment]
Looking good!  Let's submit it upstream for review.

**Pull request merged**
