### PR TITLE
abstractions to facilitate testing

### PR DESCRIPTION
**Pull request by spacejam**
- Abstract calls to Exit to facilitate testing.
- Abstract the pod status function for testing purposes.
- Fix argument ordering of Prefix checking.

@jdef

### CODE REVIEW

**Comment by sttts** [comment]
Little nit: no \* in the first commit msg line

**Comment by sttts** [comment]
The \* in the first commit... but it will be squashed anyway I guess.

**Comment by sttts** [comment]
otherwise :+1:

**Comment by spacejam** [comment]
squashed and moved to https://github.com/mesosphere/kubernetes/pull/12

**Pull request closed without merging**
