### PR TITLE
Removed deprecated reference to ElasticMesos from Mesos Getting-Started-Guide.

### PR DESCRIPTION
**Pull request by joerg84**

### CODE REVIEW

**Comment by joerg84** [comment]
We will add a new section about setting up such cluster using vagrant-mesos. The goal here is just to remove the deprecated reference asap.

**Comment by jdef** [comment]
there's still a link "[5]" that points to google.mesosphere.com (and related link in the text)

**Comment by joerg84** [comment]
@jdef PTAL

**Comment by joerg84** [comment]
Moved to:
https://github.com/GoogleCloudPlatform/kubernetes/pull/9252

**Pull request closed without merging**
