### PR TITLE
Upstream k8sm controller manager and km binary

### PR DESCRIPTION
**Pull request by tsenart**
Closes mesosphere/kubernetes-mesos#310
Depends on GoogleCloudPlatform/kubernetes#8882

TODO:
- [x] sync changes from https://github.com/mesosphere/kubernetes-mesos/commit/efa01b0f47b252890ff70f9dd09977a779d70bc7

/cc @spacejam @jdef

### CODE REVIEW

**Comment by spacejam** [comment]
lgtm :+1:

**Comment by tsenart** [comment]
PTAL (again)

**Comment by jdef** [comment]
LGTM, please squash for easy cherry-picking

**Comment by tsenart** [comment]
Will do.

**Comment by spacejam** [comment]
:+1: (again)

**Comment by jdef** [comment]
this needs a rebase, k8s/master has shifted and upstream_k8sm has been rebased accordingly.

**Comment by tsenart** [comment]
I was getting lots of conflicts when rebasing so I went around them with the following steps:
1. Squash mine and @spacejam's km work into one commit
2. Checkout a new temporary branch from upstream_k8sm
3. Cherry-pick the previously squashed commit into this
4. Reset `upstream-k8sm-controller-manager` to this temp branch
5. Force push `origin/upstream-k8sm-controller-manager`

**Comment by tsenart** [comment]
PTAL @spacejam @jdef

**Comment by tsenart** [comment]
It seems I still have to remove the imports of v1beta{1,2} from endpoints_controller.go

**Comment by jdef** [comment]
@tsenart there were a couple of recent changes that I had to make on mesosphere/kubernetes-mesos@upstream_k8sm in order to get it to build against the latest rebase. removal of the v1betaX refs from endpoints_controller was part of that.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/commit/ff41d9d2d4cac7f049d48f466567f154c20a162a

**Comment by tsenart** [comment]
I'll rebate again. Thanks James.

**Comment by tsenart** [comment]
s/rebate/rebase/

**Comment by jdef** [comment]
LGTM

**Comment by tsenart** [comment]
Closed in favour of https://github.com/GoogleCloudPlatform/kubernetes/pull/9265

**Pull request closed without merging**
